
name: "Dev Terraform Ifras Workflow"

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main  
  workflow_dispatch:    

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true  
  
jobs: 
  terraform-planning-job:
    name: terraform-planning-job 
    runs-on: raja
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: Environments/Dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: Environments/Dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: Environments/Dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: Environments/Dev
  terraform-apply:
    name: terraform-apply
    runs-on: raja
    needs: terraform-planning-job
    # if: github.ref == 'refs/heads/main'
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: Environments/Dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: Environments/Dev  







        